version: '3'

services: 
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: install
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8010:3000
    environment:
      # make hot-reloading work.
      - CHOKIDAR_USEPOLLING=true # maybe obsolete?
      - WDS_SOCKET_PORT=0
      # run node in development mode
      - NODE_ENV=development
      # set ops env to local
      - REACT_APP_OPS_ENV=local
    command: yarn start