name: 'Test'
on:
  push:
    branches:
      # TODO: change to main
      - 46-provide-staging-deployment-client

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: 'Build Dist'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'
      - name: 'Install Dependencies'
        run: yarn install
      - name: 'Run Linter'
        run: yarn build
      - name: Save dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: dist
